version = 0.1

[default.deploy.parameters]
stack_name = "soccer-league-backend"
s3_bucket = "soccer-league-sam-deploys"
s3_prefix = "soccer-league-backend"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
no_fail_on_empty_changeset = true 