AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Soccer League Management REST API (Express + DynamoDB)

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 512

Resources:
  SoccerLeagueApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/server.handler
      CodeUri: .
      Environment:
        Variables:
          LEAGUES_TABLE: SL-LeaguesTable
          TEAMS_TABLE: SL-TeamsTable
          PLAYERS_TABLE: SL-PlayersTable
          GAMES_TABLE: SL-GamesTable
          USERS_TABLE: SL-UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: SL-LeaguesTable
        - DynamoDBCrudPolicy:
            TableName: SL-TeamsTable
        - DynamoDBCrudPolicy:
            TableName: SL-PlayersTable
        - DynamoDBCrudPolicy:
            TableName: SL-GamesTable
        - DynamoDBCrudPolicy:
            TableName: SL-UsersTable

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
